### ISSUE TITLE
This repo is not recommended due to more risks of block.

### ISSUE THREAD

**Issue by nessusing** [ai-eks/OpenClubhouse#6]
https://opench.aix.uy/ can't play audio any more, so is my own instance.

**Comment by ai-eks** [comment]
The worker account is blocked, so it cannot play voice anymore.

**Comment by davidfregoli** [comment]
so if I setup my own instance with my own secret it still won't work?

**Comment by ai-eks** [comment]
@davidfregoli If you setup both this repo and worker, it can work well now. However, because that the worker should join all channels, which is visible for everyone, may cause the ban of your account. I recommend that invited users can use other third-party client to use Clubhouse. You can find several repos on GitHub by searching Clubhouse.

**Comment by nessusing** [comment]
I had my own instance up yesterday, was also banned within the same day...

**Comment by TekuSP** [comment]
Was this code copied? No?
Then this is legal. Open Source lives forever, Intel decompiled AMD64 architecture too!
