### ISSUE TITLE
Failed to play the channel

### ISSUE THREAD

**Issue by mostafasayed33** [ai-eks/OpenClubhouse#9]
Joining channel failed, rollback n {name: "AgoraRTCException", code: "CAN_NOT_GET_GATEWAY_SERVER", message: "AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: no active status"

AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: no active status

and AgoraRTC_N-production.js.map is missing

**Comment by ai-eks** [comment]
I can't test any more due to no available account, so I can't detect the reason. The error message seems the Gateway servers are not active. Maybe you can change a channel or wait a moment to have another try. 

The file AgoraRTC_N-production.js.map is useless, and Agora doesn't provide it in SDK package.

**Comment by tsecret** [comment]
I have the same error, I am pretty sure I am using the correct details.
Let me know if you have solved the issue. Thanks!

**Comment by kjfcpua** [comment]
是账号被封,网站关闭了？
